### ISSUE TITLE
SHA256 Missmatch on centos 8 repo package.

### ISSUE THREAD

**Issue by jonasled** [RIPE-NCC/ripe-atlas-probe-doc#34]
Hi,
I just  wanted to install a software probe on EL8, but the SHA256 missmatches with the given Hash in the documentation (manuals/CentOS-8-binary.en.md)
The Hash I calculated: f33c27745f2bd87344be790465ef984a972fd539dc83bd4f61d4242c607ef1ee

**Comment by jonasled** [comment]
Oh, OK the file was deleted on the server and is only returning a 404 page.

**Comment by P1Fanatic** [comment]
I have same issue. Running CentOS 7 on Docker I get:

3cbaa92f4a1dc4c74a865a6c14c3cda0badb649ee18d561740a2ba229b3e1e63  ripe-atlas-repo-1-3.el7.noarch.rpm

I proceeded with install anyway but last part says about registering the SW probe and that probe software generates a new SSH key pair located in /var/atlas-probe/etc/probe_key.pub which does not exist.

Any ideas?

**Comment by kotenok2000** [comment]
Try to run sudo systemctl enable atlas
and then sudo systemctl start atlas

**Comment by michel-stam** [comment]
Hi guys,

Did a check for you just now. This should be the correct sha256sums for the RPMS:

CentOS7:
- ripe-atlas-repo-1-3.el7.noarch.rpm 3cbaa92f4a1dc4c74a865a6c14c3cda0badb649ee18d561740a2ba229b3e1e63
- atlasswprobe-5080-1.el7.x86_64.rpm 4e849e169ce9bf5ee890926cb8ee6fb5993f0caae7a7c21afc0cc3f4f7e81ab6 

CentOS8:
- ripe-atlas-repo-1-3.el8.noarch.rpm e1e7800666f6978eb2e78dfabcd8aa0fa0ca45d9e97cc861a5e93300a2e46a00
- atlasswprobe-5080-1.el8.x86_64.rpm 4cca7fddf82fc926ae05fe04c419b5558fd2c41c4364d15d453ecc440b02055c 

It's possible the documentation did not get updated yet.

Cheers,

Michel (RIPE NCC)

**Comment by lhestina** [comment]
Documentation updated.
