### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by ShadowLabs-Offical** [RIPE-NCC/ripe-atlas-probe-doc#40]
Documents seem to be oudated vs which operarting systems are EOL or outdated. Is there a template or another doc that has updated os requirments or image builds with a CI/CD pipeline to contribute to? I'd love to help however i can.

Thanks in advance,
Taylor L.

**Comment by michel-stam** [comment]
Hi Taylor,

Thank you for contacting. We're on the verge of releasing a new version of the probe, we will have a look at the documentation, pull requests are welcome :)

regards,

Michel

**Comment by ShadowLabs-Offical** [comment]
Thanks for the quick reply. Can you tell me what requirements will need to be met for the new probe client as then i can try to get started on the documentation since both RHEL based distos are EOL and Debian 9 is EOL and Debian 10 is EOL June30,2024

**Comment by michel-stam** [comment]
Hello @shadow-security1,

The new version will be a complete restructure of the existing probe, both in packages and in directories. Supported distributions as yet CentOS8, Oracle EL8, Oracle EL9 (so technically RHEL 8 and 9). All on the x86_64 platform.

Debian will be supported a bit later, we need to do some rework, although the initial code is already there. OpenWRT will follow after that, likely somewhere August, it is in a similar state as the Debian support. Support will be for Debian 11 and 12, Debian 10 is not supported anymore. OpenWRT will be tested on 22.03.

As to the restructuring;
1. /var/atlas-probe/crons/ -> /var/spool/ripe-atlas/crons/
2. /var/atlas-probe/data -> /var/spool/ripe-atlas/data/
3. /usr/local/atlas/bin/ -> /usr/libexec/ripe-atlas/scripts/
4. /usr/local/atlas/bb-13.3/ /usr/libexec/ripe-atlas/measurement/
5. /usr/local/atlas/bin/ATLAS -> /usr/sbin/ripe-atlas
6. /var/atlas-probe/state/mode -> /etc/ripe-atlas/mode
7. /var/atlas-probe/bin/ -> /etc/ripe-atlas/
8. /var/atlas-probe/etc/probe_key* -> /etc/ripe-atlas/probe_key*
9. /var/atlas-probe/state/FIRMWARE_APPS_VERSION -> /usr/share/ripe-atlas/FIRMWARE_APPS_VERISON
10. /var/atlas-probe/run/ -> /run/ripe-atlas/pids/
11. /var/atlas-probe/status/ -> /run/ripe-atlas/status/
12. /usr/lib/systemd/system/atlas.service -> /usr/lib/systemd/system/ripe-atlas.service
Several files will be added for systemd-tmpfiles and systemd-sysusers as well.

As to the packages, this will consist of a ripe-atlas-common package that contains the functionality, and a ripe-atlas-probe package that gives the probe its purpose. There is also a ripe-atlas-anchor package to create an anchor, but this will not work without support from the Atlas team (as it requires configuration on the infrastructure too).

I hope this helps, but if not feel free to reach out to me directly and I'll see about providing you with more information.

Regards,

Michel
